# configs/callbacks/default.yaml

checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: checkpoints/${experiment_name}
  filename: model-{epoch:02d}-{val/acc:.3f}
  monitor: val/acc
  mode: max
  save_top_k: 3
  save_last: true

early_stopping:
  _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: val/acc
  patience: 5
  mode: max
